import { cpSync, mkdirSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
execFileSync(process.execPath, [resolve(root, 'scripts/generate-print.mjs')], { stdio: 'inherit' });
execFileSync(process.execPath, [resolve(root, 'scripts/package-standalone.mjs')], { stdio: 'inherit' });
execFileSync(process.execPath, [resolve(root, 'scripts/check-syntax.mjs')], { stdio: 'inherit' });
execFileSync(process.execPath, [resolve(root, 'scripts/validate-map.mjs')], { stdio: 'inherit' });
const printSource = readFileSync(resolve(root, 'print.html'));
const expectedHash = createHash('sha256').update(printSource).digest('hex');
const printedHash = readFileSync(resolve(root, 'output/pdf/print-source.sha256'), 'utf8').trim();
if (expectedHash !== printedHash) throw new Error('Print booklet is outdated. Run python3 scripts/generate-pdf.py and rebuild.');
mkdirSync(resolve(root, 'dist'), { recursive: true });
cpSync(resolve(root, 'index.html'), resolve(root, 'dist/index.html'));
cpSync(resolve(root, 'print.html'), resolve(root, 'dist/print.html'));
cpSync(resolve(root, 'output/pdf/topo-italie-printboek.pdf'), resolve(root, 'dist/printboek.pdf'));
mkdirSync(resolve(root, 'dist/scripts'), { recursive: true });
cpSync(resolve(root, 'scripts/learning-engine.js'), resolve(root, 'dist/scripts/learning-engine.js'));
console.log('Static build: dist/index.html, dist/print.html, dist/printboek.pdf');
