import { readFileSync } from 'node:fs';
import { Script } from 'node:vm';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const heroArt = readFileSync(new URL('../output/art/topo-italie-avontuur.webp', import.meta.url)).toString('base64');
const ninoArt = readFileSync(new URL('../output/art/nino-op-de-scooter.webp', import.meta.url)).toString('base64');
if (!html.includes(`<img src="data:image/webp;base64,${heroArt}"`)) throw new Error('Route panorama differs from its source WebP');
if (!html.includes(`--nino-art:url("data:image/webp;base64,${ninoArt}")`)) throw new Error('Nino artwork differs from its source WebP');
const scripts = [...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)];
const inline = scripts.filter(match => !match[1].includes('src='));
if (inline.length !== 3 || scripts.length !== 3) throw new Error(`Expected three self-contained scripts, found ${inline.length}`);
const engine = readFileSync(new URL('./learning-engine.js', import.meta.url), 'utf8').trim();
if (inline[0][2].trim() !== engine) throw new Error('Inline engine differs from tested learning engine');
const routeEngine = readFileSync(new URL('./route-engine.js', import.meta.url), 'utf8').trim();
if (inline[1][2].trim() !== routeEngine) throw new Error('Inline route engine differs from tested route engine');
inline.forEach((match, index) => new Script(match[2], { filename: `index.html:inline-${index}.js` }));
const printHtml = readFileSync(new URL('../print.html', import.meta.url), 'utf8');
const printCode = printHtml.match(/<script>([\s\S]*?)<\/script>/)?.[1];
if (!printCode) throw new Error('Printable map script missing');
new Script(printCode, { filename: 'print.html:inline.js' });
const standalone = readFileSync(new URL('../output/html/topo-italie-interactief.html', import.meta.url), 'utf8');
const bundled = [...standalone.matchAll(/<script>([\s\S]*?)<\/script>/g)];
if (bundled.length !== 3 || standalone !== html) throw new Error('Downloaded HTML must equal the one-file app exactly');
if (readFileSync(new URL('../output/html/topo-italie-duolingo.html', import.meta.url), 'utf8') !== html) throw new Error('New route download differs from canonical app');
bundled.forEach((match, index) => new Script(match[1], { filename: `standalone:script-${index}` }));
console.log('App, print page, standalone bundle and learning engine JavaScript syntax: OK');
